name: antitrust
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy==1.23.5
  - pandas==1.5.2
  - requests==2.28.1
  - beautifulsoup4==4.11.1
  - ipykernel==6.17.1
  - os==2.1.4
  - openpyxl==3.0.10
  - spacy==3.4.3
  - spacy-legacy==3.0.10
  - spacy-loggers==1.0.3
  - nltk==3.7
  - pycountry==22.3.5
  - langdetect==1.0.9